from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.product_list, name='product_list'),
    path('categories/<slug:slug>/', views.category_products, name='category_products'),
    path('products/<slug:slug>/', views.product_detail, name='product_detail'),
    path('register/', views.register, name='register'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('about/', views.about_us, name='about_us'),
    path('gallery/products/', views.product_gallery, name='product_gallery'),
    path('gallery/', views.gallery, name='gallery'),
    path('sell/', views.sell_product, name='sell_product'),
    path('contact/', views.contact_us, name='contact_us'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('my-orders/', views.my_orders, name='my_orders'),
    path('razorpay/initiate/', views.initiate_payment, name='initiate_payment'),
    path('razorpay/verify/', views.verify_payment, name='verify_payment'),
    path('razorpay/<int:order_id>/', views.razorpay_payment, name='razorpay_payment'),
    path('razorpay/verify/<int:order_id>/', views.verify_razorpay_payment, name='verify_razorpay_payment'),
    path('review/<slug:slug>/', views.submit_review, name='submit_review'),
    path('wishlist/add/<slug:slug>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('cart/add/<slug:category_slug>/<slug:product_slug>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('razorpay/', views.razorpay_payment, name='razorpay_payment'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('refund-policy/', views.refund_policy, name='refund_policy'),
    path('shipping-policy/', views.shipping_policy, name='shipping_policy'),
    path('terms-and-conditions/', views.terms_and_conditions, name='terms_and_conditions'),
    path('our-mission/', views.mission, name='mission'),
    path('our-vision/', views.vision, name='vision'),
]
