# Generated by Django 6.0.3 on 2026-04-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='results_pics/'),
        ),
    ]
